services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
      - mysql_db
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - laravel

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - laravel
    environment:
      MONGO_INITDB_ROOT_USERNAME: ariyadel12
      MONGO_INITDB_ROOT_PASSWORD: 6Z7MT=fe%tr%zcE9
      MONGO_INITDB_DATABASE: analytics_db

  # 🟢 سرویس MySQL با پورت و اطلاعات کاربری به روز شده
  mysql_db:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3307:3306" # پورت هاست به 3307 تغییر یافت تا با XAMPP تداخل نداشته باشد
    environment:
      MYSQL_ROOT_PASSWORD: 6Z7MT=fe%tr%zcE9 # 🟢 تغییر: رمز عبور root به رمز دلخواه شما
      MYSQL_DATABASE: myshop_db
      MYSQL_USER: ariyadel12 # 🟢 تغییر: نام کاربری به ariyadel12
      MYSQL_PASSWORD: 6Z7MT=fe%tr%zcE9 # 🟢 تغییر: رمز عبور کاربر به رمز دلخواه شما
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  # 🟢 سرویس PhpMyAdmin با اطلاعات کاربری به روز شده
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_interface
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: 6Z7MT=fe%tr%zcE9 # 🟢 تغییر: رمز عبور root به رمز دلخواه شما
    depends_on:
      - mysql_db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
