services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www                      # کل پروژه
      - ./vendor:/var/www/vendor        # کش vendor (composer)
      - ./storage:/var/www/storage      # کش storage (دیتا، لاگ و ...)
      - ./storage/keys:/var/www/storage/keys # پوشه کلیدهای JWE
    depends_on:
      - redis
      - mongodb
      - mysql_db
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # <-- اینجا مسیر درست به default.conf هست
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - laravel
    volumes:
      - ./docker/redis/data:/data

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - laravel
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - ./docker/mongo/data:/data/db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_interface
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
