services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - laravel

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
