services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - laravel

  mongodb:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - laravel
    environment: # 🟢 جدید: اضافه کردن متغیرهای محیطی برای احراز هویت
      MONGO_INITDB_ROOT_USERNAME: ariyadel12 # 👈 نام کاربری شما از فایل .env
      MONGO_INITDB_ROOT_PASSWORD: 6Z7MT=fe%tr%zcE9 # 👈 رمز عبور شما از فایل .env
      MONGO_INITDB_DATABASE: analytics_db # دیتابیس پیش‌فرض برای کاربر روت (اختیاری)

networks:
  laravel:
    driver: bridge
